
title: Human Brain Pharmacome
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description:  Mechanism-based chemoinformatics and drug repositioning for dementia

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
